/*
 * Interface wrapper code.
 *
 * Generated by SIP 5.3.0
 *
 * Copyright (c) 2019 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt5.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtDBus.h"

#line 26 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/sip/QtDBus/qdbusservicewatcher.sip"
#include <qdbusservicewatcher.h>
#line 29 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/QtDBus/sipQtDBusQDBusServiceWatcherWatchMode.cpp"

#line 26 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/sip/QtDBus/qdbusservicewatcher.sip"
#include <qdbusservicewatcher.h>
#line 33 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/QtDBus/sipQtDBusQDBusServiceWatcherWatchMode.cpp"


extern "C" {static long slot_QDBusServiceWatcher_WatchMode___hash__(PyObject *);}
static long slot_QDBusServiceWatcher_WatchMode___hash__(PyObject *sipSelf)
{
     ::QDBusServiceWatcher::WatchMode *sipCpp = reinterpret_cast< ::QDBusServiceWatcher::WatchMode *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QDBusServiceWatcher_WatchMode));

    if (!sipCpp)
        return 0L;


    {
        {
            long sipRes = 0;

#line 116 "sip/QtCore/qglobal.sip"
        sipRes = sipCpp->operator QDBusServiceWatcher::WatchMode::Int();
#line 51 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/QtDBus/sipQtDBusQDBusServiceWatcherWatchMode.cpp"

            return sipRes;
        }
    }

    return 0;
}


extern "C" {static int slot_QDBusServiceWatcher_WatchMode___bool__(PyObject *);}
static int slot_QDBusServiceWatcher_WatchMode___bool__(PyObject *sipSelf)
{
     ::QDBusServiceWatcher::WatchMode *sipCpp = reinterpret_cast< ::QDBusServiceWatcher::WatchMode *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QDBusServiceWatcher_WatchMode));

    if (!sipCpp)
        return -1;


    {
        {
            int sipRes = 0;

#line 111 "sip/QtCore/qglobal.sip"
        sipRes = (sipCpp->operator QDBusServiceWatcher::WatchMode::Int() != 0);
#line 76 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/QtDBus/sipQtDBusQDBusServiceWatcherWatchMode.cpp"

            return sipRes;
        }
    }

    return 0;
}


extern "C" {static PyObject *slot_QDBusServiceWatcher_WatchMode___ne__(PyObject *,PyObject *);}
static PyObject *slot_QDBusServiceWatcher_WatchMode___ne__(PyObject *sipSelf,PyObject *sipArg)
{
     ::QDBusServiceWatcher::WatchMode *sipCpp = reinterpret_cast< ::QDBusServiceWatcher::WatchMode *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QDBusServiceWatcher_WatchMode));

    if (!sipCpp)
        return SIP_NULLPTR;

    PyObject *sipParseErr = SIP_NULLPTR;

    {
        const  ::QDBusServiceWatcher::WatchMode* a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QDBusServiceWatcher_WatchMode, &a0, &a0State))
        {
            bool sipRes = 0;

#line 106 "sip/QtCore/qglobal.sip"
        sipRes = (sipCpp->operator QDBusServiceWatcher::WatchMode::Int() != a0->operator QDBusServiceWatcher::WatchMode::Int());
#line 106 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/QtDBus/sipQtDBusQDBusServiceWatcherWatchMode.cpp"
            sipReleaseType(const_cast< ::QDBusServiceWatcher::WatchMode *>(a0),sipType_QDBusServiceWatcher_WatchMode,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return SIP_NULLPTR;

    return sipPySlotExtend(&sipModuleAPI_QtDBus, ne_slot, sipType_QDBusServiceWatcher_WatchMode, sipSelf, sipArg);
}


extern "C" {static PyObject *slot_QDBusServiceWatcher_WatchMode___eq__(PyObject *,PyObject *);}
static PyObject *slot_QDBusServiceWatcher_WatchMode___eq__(PyObject *sipSelf,PyObject *sipArg)
{
     ::QDBusServiceWatcher::WatchMode *sipCpp = reinterpret_cast< ::QDBusServiceWatcher::WatchMode *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QDBusServiceWatcher_WatchMode));

    if (!sipCpp)
        return SIP_NULLPTR;

    PyObject *sipParseErr = SIP_NULLPTR;

    {
        const  ::QDBusServiceWatcher::WatchMode* a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QDBusServiceWatcher_WatchMode, &a0, &a0State))
        {
            bool sipRes = 0;

#line 101 "sip/QtCore/qglobal.sip"
        sipRes = (sipCpp->operator QDBusServiceWatcher::WatchMode::Int() == a0->operator QDBusServiceWatcher::WatchMode::Int());
#line 142 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/QtDBus/sipQtDBusQDBusServiceWatcherWatchMode.cpp"
            sipReleaseType(const_cast< ::QDBusServiceWatcher::WatchMode *>(a0),sipType_QDBusServiceWatcher_WatchMode,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return SIP_NULLPTR;

    return sipPySlotExtend(&sipModuleAPI_QtDBus, eq_slot, sipType_QDBusServiceWatcher_WatchMode, sipSelf, sipArg);
}


extern "C" {static PyObject *slot_QDBusServiceWatcher_WatchMode___ixor__(PyObject *,PyObject *);}
static PyObject *slot_QDBusServiceWatcher_WatchMode___ixor__(PyObject *sipSelf,PyObject *sipArg)
{
    if (!PyObject_TypeCheck(sipSelf, sipTypeAsPyTypeObject(sipType_QDBusServiceWatcher_WatchMode)))
    {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }

     ::QDBusServiceWatcher::WatchMode *sipCpp = reinterpret_cast< ::QDBusServiceWatcher::WatchMode *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QDBusServiceWatcher_WatchMode));

    if (!sipCpp)
        return SIP_NULLPTR;

    PyObject *sipParseErr = SIP_NULLPTR;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1i", &a0))
        {
#line 95 "sip/QtCore/qglobal.sip"
        *sipCpp = QDBusServiceWatcher::WatchMode(*sipCpp ^ a0);
#line 181 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/QtDBus/sipQtDBusQDBusServiceWatcherWatchMode.cpp"

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return SIP_NULLPTR;

    PyErr_Clear();

    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}


extern "C" {static PyObject *slot_QDBusServiceWatcher_WatchMode___xor__(PyObject *,PyObject *);}
static PyObject *slot_QDBusServiceWatcher_WatchMode___xor__(PyObject *sipArg0,PyObject *sipArg1)
{
    PyObject *sipParseErr = SIP_NULLPTR;

    {
         ::QDBusServiceWatcher::WatchMode* a0;
        int a0State = 0;
        int a1;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J1i", sipType_QDBusServiceWatcher_WatchMode, &a0, &a0State, &a1))
        {
             ::QDBusServiceWatcher::WatchMode*sipRes;

            sipRes = new  ::QDBusServiceWatcher::WatchMode((*a0 ^ a1));
            sipReleaseType(a0,sipType_QDBusServiceWatcher_WatchMode,a0State);

            return sipConvertFromNewType(sipRes,sipType_QDBusServiceWatcher_WatchMode,SIP_NULLPTR);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return SIP_NULLPTR;

    return sipPySlotExtend(&sipModuleAPI_QtDBus, xor_slot, SIP_NULLPTR, sipArg0, sipArg1);
}


extern "C" {static PyObject *slot_QDBusServiceWatcher_WatchMode___ior__(PyObject *,PyObject *);}
static PyObject *slot_QDBusServiceWatcher_WatchMode___ior__(PyObject *sipSelf,PyObject *sipArg)
{
    if (!PyObject_TypeCheck(sipSelf, sipTypeAsPyTypeObject(sipType_QDBusServiceWatcher_WatchMode)))
    {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }

     ::QDBusServiceWatcher::WatchMode *sipCpp = reinterpret_cast< ::QDBusServiceWatcher::WatchMode *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QDBusServiceWatcher_WatchMode));

    if (!sipCpp)
        return SIP_NULLPTR;

    PyObject *sipParseErr = SIP_NULLPTR;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1i", &a0))
        {
#line 89 "sip/QtCore/qglobal.sip"
        *sipCpp = QDBusServiceWatcher::WatchMode(*sipCpp | a0);
#line 253 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/QtDBus/sipQtDBusQDBusServiceWatcherWatchMode.cpp"

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return SIP_NULLPTR;

    PyErr_Clear();

    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}


extern "C" {static PyObject *slot_QDBusServiceWatcher_WatchMode___or__(PyObject *,PyObject *);}
static PyObject *slot_QDBusServiceWatcher_WatchMode___or__(PyObject *sipArg0,PyObject *sipArg1)
{
    PyObject *sipParseErr = SIP_NULLPTR;

    {
         ::QDBusServiceWatcher::WatchMode* a0;
        int a0State = 0;
        int a1;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J1i", sipType_QDBusServiceWatcher_WatchMode, &a0, &a0State, &a1))
        {
             ::QDBusServiceWatcher::WatchMode*sipRes;

            sipRes = new  ::QDBusServiceWatcher::WatchMode((*a0 | a1));
            sipReleaseType(a0,sipType_QDBusServiceWatcher_WatchMode,a0State);

            return sipConvertFromNewType(sipRes,sipType_QDBusServiceWatcher_WatchMode,SIP_NULLPTR);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return SIP_NULLPTR;

    return sipPySlotExtend(&sipModuleAPI_QtDBus, or_slot, SIP_NULLPTR, sipArg0, sipArg1);
}


extern "C" {static PyObject *slot_QDBusServiceWatcher_WatchMode___iand__(PyObject *,PyObject *);}
static PyObject *slot_QDBusServiceWatcher_WatchMode___iand__(PyObject *sipSelf,PyObject *sipArg)
{
    if (!PyObject_TypeCheck(sipSelf, sipTypeAsPyTypeObject(sipType_QDBusServiceWatcher_WatchMode)))
    {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }

     ::QDBusServiceWatcher::WatchMode *sipCpp = reinterpret_cast< ::QDBusServiceWatcher::WatchMode *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QDBusServiceWatcher_WatchMode));

    if (!sipCpp)
        return SIP_NULLPTR;

    PyObject *sipParseErr = SIP_NULLPTR;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1i", &a0))
        {
            sipCpp-> ::QDBusServiceWatcher::WatchMode::operator&=(a0);

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return SIP_NULLPTR;

    PyErr_Clear();

    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}


extern "C" {static PyObject *slot_QDBusServiceWatcher_WatchMode___and__(PyObject *,PyObject *);}
static PyObject *slot_QDBusServiceWatcher_WatchMode___and__(PyObject *sipArg0,PyObject *sipArg1)
{
    PyObject *sipParseErr = SIP_NULLPTR;

    {
         ::QDBusServiceWatcher::WatchMode* a0;
        int a0State = 0;
        int a1;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J1i", sipType_QDBusServiceWatcher_WatchMode, &a0, &a0State, &a1))
        {
             ::QDBusServiceWatcher::WatchMode*sipRes;

            sipRes = new  ::QDBusServiceWatcher::WatchMode((*a0 & a1));
            sipReleaseType(a0,sipType_QDBusServiceWatcher_WatchMode,a0State);

            return sipConvertFromNewType(sipRes,sipType_QDBusServiceWatcher_WatchMode,SIP_NULLPTR);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return SIP_NULLPTR;

    return sipPySlotExtend(&sipModuleAPI_QtDBus, and_slot, SIP_NULLPTR, sipArg0, sipArg1);
}


extern "C" {static PyObject *slot_QDBusServiceWatcher_WatchMode___invert__(PyObject *);}
static PyObject *slot_QDBusServiceWatcher_WatchMode___invert__(PyObject *sipSelf)
{
     ::QDBusServiceWatcher::WatchMode *sipCpp = reinterpret_cast< ::QDBusServiceWatcher::WatchMode *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QDBusServiceWatcher_WatchMode));

    if (!sipCpp)
        return SIP_NULLPTR;


    {
        {
             ::QDBusServiceWatcher::WatchMode*sipRes;

            sipRes = new  ::QDBusServiceWatcher::WatchMode(~(*sipCpp));

            return sipConvertFromNewType(sipRes,sipType_QDBusServiceWatcher_WatchMode,SIP_NULLPTR);
        }
    }

    return 0;
}


extern "C" {static PyObject *slot_QDBusServiceWatcher_WatchMode___int__(PyObject *);}
static PyObject *slot_QDBusServiceWatcher_WatchMode___int__(PyObject *sipSelf)
{
     ::QDBusServiceWatcher::WatchMode *sipCpp = reinterpret_cast< ::QDBusServiceWatcher::WatchMode *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QDBusServiceWatcher_WatchMode));

    if (!sipCpp)
        return SIP_NULLPTR;


    {
        {
            int sipRes;

            sipRes = *sipCpp;

            return PyLong_FromLong(sipRes);
        }
    }

    return 0;
}


/* Call the instance's destructor. */
extern "C" {static void release_QDBusServiceWatcher_WatchMode(void *, int);}
static void release_QDBusServiceWatcher_WatchMode(void *sipCppV, int)
{
    delete reinterpret_cast< ::QDBusServiceWatcher::WatchMode *>(sipCppV);
}


extern "C" {static void *array_QDBusServiceWatcher_WatchMode(Py_ssize_t);}
static void *array_QDBusServiceWatcher_WatchMode(Py_ssize_t sipNrElem)
{
    return new  ::QDBusServiceWatcher::WatchMode[sipNrElem];
}


extern "C" {static void assign_QDBusServiceWatcher_WatchMode(void *, Py_ssize_t, void *);}
static void assign_QDBusServiceWatcher_WatchMode(void *sipDst, Py_ssize_t sipDstIdx, void *sipSrc)
{
    reinterpret_cast< ::QDBusServiceWatcher::WatchMode *>(sipDst)[sipDstIdx] = *reinterpret_cast< ::QDBusServiceWatcher::WatchMode *>(sipSrc);
}


extern "C" {static void *copy_QDBusServiceWatcher_WatchMode(const void *, Py_ssize_t);}
static void *copy_QDBusServiceWatcher_WatchMode(const void *sipSrc, Py_ssize_t sipSrcIdx)
{
    return new  ::QDBusServiceWatcher::WatchMode(reinterpret_cast<const  ::QDBusServiceWatcher::WatchMode *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_QDBusServiceWatcher_WatchMode(sipSimpleWrapper *);}
static void dealloc_QDBusServiceWatcher_WatchMode(sipSimpleWrapper *sipSelf)
{
    if (sipIsOwnedByPython(sipSelf))
    {
        release_QDBusServiceWatcher_WatchMode(sipGetAddress(sipSelf), 0);
    }
}


extern "C" {static void *init_type_QDBusServiceWatcher_WatchMode(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_QDBusServiceWatcher_WatchMode(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
     ::QDBusServiceWatcher::WatchMode *sipCpp = SIP_NULLPTR;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, SIP_NULLPTR, sipUnused, ""))
        {
            sipCpp = new  ::QDBusServiceWatcher::WatchMode();

            return sipCpp;
        }
    }

    {
        int a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, SIP_NULLPTR, sipUnused, "i", &a0))
        {
            sipCpp = new  ::QDBusServiceWatcher::WatchMode(a0);

            return sipCpp;
        }
    }

    {
        const  ::QDBusServiceWatcher::WatchMode* a0;
        int a0State = 0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, SIP_NULLPTR, sipUnused, "J1", sipType_QDBusServiceWatcher_WatchMode, &a0, &a0State))
        {
            sipCpp = new  ::QDBusServiceWatcher::WatchMode(*a0);
            sipReleaseType(const_cast< ::QDBusServiceWatcher::WatchMode *>(a0),sipType_QDBusServiceWatcher_WatchMode,a0State);

            return sipCpp;
        }
    }

    return SIP_NULLPTR;
}


extern "C" {static int convertTo_QDBusServiceWatcher_WatchMode(PyObject *, void **, int *, PyObject *);}
static int convertTo_QDBusServiceWatcher_WatchMode(PyObject *sipPy,void **sipCppPtrV,int *sipIsErr,PyObject *sipTransferObj)
{
     ::QDBusServiceWatcher::WatchMode **sipCppPtr = reinterpret_cast< ::QDBusServiceWatcher::WatchMode **>(sipCppPtrV);

#line 121 "sip/QtCore/qglobal.sip"
// Allow an instance of the base enum whenever a QDBusServiceWatcher::WatchMode is expected.

if (sipIsErr == NULL)
    return (PyObject_TypeCheck(sipPy, sipTypeAsPyTypeObject(sipType_QDBusServiceWatcher_WatchModeFlag)) ||
            sipCanConvertToType(sipPy, sipType_QDBusServiceWatcher_WatchMode, SIP_NO_CONVERTORS));

if (PyObject_TypeCheck(sipPy, sipTypeAsPyTypeObject(sipType_QDBusServiceWatcher_WatchModeFlag)))
{
    *sipCppPtr = new QDBusServiceWatcher::WatchMode(int(SIPLong_AsLong(sipPy)));

    return sipGetState(sipTransferObj);
}

*sipCppPtr = reinterpret_cast<QDBusServiceWatcher::WatchMode *>(sipConvertToType(sipPy, sipType_QDBusServiceWatcher_WatchMode, sipTransferObj, SIP_NO_CONVERTORS, 0, sipIsErr));

return 0;
#line 521 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/QtDBus/sipQtDBusQDBusServiceWatcherWatchMode.cpp"
}


/* Define this type's Python slots. */
static sipPySlotDef slots_QDBusServiceWatcher_WatchMode[] = {
    {(void *)slot_QDBusServiceWatcher_WatchMode___hash__, hash_slot},
    {(void *)slot_QDBusServiceWatcher_WatchMode___bool__, bool_slot},
    {(void *)slot_QDBusServiceWatcher_WatchMode___ne__, ne_slot},
    {(void *)slot_QDBusServiceWatcher_WatchMode___eq__, eq_slot},
    {(void *)slot_QDBusServiceWatcher_WatchMode___ixor__, ixor_slot},
    {(void *)slot_QDBusServiceWatcher_WatchMode___xor__, xor_slot},
    {(void *)slot_QDBusServiceWatcher_WatchMode___ior__, ior_slot},
    {(void *)slot_QDBusServiceWatcher_WatchMode___or__, or_slot},
    {(void *)slot_QDBusServiceWatcher_WatchMode___iand__, iand_slot},
    {(void *)slot_QDBusServiceWatcher_WatchMode___and__, and_slot},
    {(void *)slot_QDBusServiceWatcher_WatchMode___invert__, invert_slot},
    {(void *)slot_QDBusServiceWatcher_WatchMode___int__, int_slot},
    {0, (sipPySlotType)0}
};

PyDoc_STRVAR(doc_QDBusServiceWatcher_WatchMode, "\1QDBusServiceWatcher.WatchMode()\n"
"QDBusServiceWatcher.WatchMode(Union[QDBusServiceWatcher.WatchMode, QDBusServiceWatcher.WatchModeFlag])\n"
"QDBusServiceWatcher.WatchMode(QDBusServiceWatcher.WatchMode)");


static pyqt5ClassPluginDef plugin_QDBusServiceWatcher_WatchMode = {
    SIP_NULLPTR,
    1,
    SIP_NULLPTR,
    SIP_NULLPTR
};


sipClassTypeDef sipTypeDef_QtDBus_QDBusServiceWatcher_WatchMode = {
    {
        -1,
        SIP_NULLPTR,
        SIP_NULLPTR,
        SIP_TYPE_SUPER_INIT|SIP_TYPE_LIMITED_API|SIP_TYPE_CLASS,
        sipNameNr_QDBusServiceWatcher__WatchMode,
        SIP_NULLPTR,
        &plugin_QDBusServiceWatcher_WatchMode
    },
    {
        sipNameNr_WatchMode,
        {30, 255, 0},
        0, SIP_NULLPTR,
        0, SIP_NULLPTR,
        0, SIP_NULLPTR,
        {SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR},
    },
    doc_QDBusServiceWatcher_WatchMode,
    -1,
    sipNameNr_sip_simplewrapper,
    SIP_NULLPTR,
    slots_QDBusServiceWatcher_WatchMode,
    init_type_QDBusServiceWatcher_WatchMode,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    dealloc_QDBusServiceWatcher_WatchMode,
    assign_QDBusServiceWatcher_WatchMode,
    array_QDBusServiceWatcher_WatchMode,
    copy_QDBusServiceWatcher_WatchMode,
    release_QDBusServiceWatcher_WatchMode,
    SIP_NULLPTR,
    convertTo_QDBusServiceWatcher_WatchMode,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR
};
