/*
 * Interface wrapper code.
 *
 * Generated by SIP 5.3.0
 *
 * Copyright (c) 2019 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt5.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtNetwork.h"

#line 86 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/sip/QtNetwork/qnetworkinterface.sip"
#include <qnetworkinterface.h>
#line 29 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/QtNetwork/sipQtNetworkQNetworkInterfaceInterfaceFlags.cpp"

#line 86 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/sip/QtNetwork/qnetworkinterface.sip"
#include <qnetworkinterface.h>
#line 33 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/QtNetwork/sipQtNetworkQNetworkInterfaceInterfaceFlags.cpp"


extern "C" {static long slot_QNetworkInterface_InterfaceFlags___hash__(PyObject *);}
static long slot_QNetworkInterface_InterfaceFlags___hash__(PyObject *sipSelf)
{
     ::QNetworkInterface::InterfaceFlags *sipCpp = reinterpret_cast< ::QNetworkInterface::InterfaceFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QNetworkInterface_InterfaceFlags));

    if (!sipCpp)
        return 0L;


    {
        {
            long sipRes = 0;

#line 116 "sip/QtCore/qglobal.sip"
        sipRes = sipCpp->operator QNetworkInterface::InterfaceFlags::Int();
#line 51 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/QtNetwork/sipQtNetworkQNetworkInterfaceInterfaceFlags.cpp"

            return sipRes;
        }
    }

    return 0;
}


extern "C" {static int slot_QNetworkInterface_InterfaceFlags___bool__(PyObject *);}
static int slot_QNetworkInterface_InterfaceFlags___bool__(PyObject *sipSelf)
{
     ::QNetworkInterface::InterfaceFlags *sipCpp = reinterpret_cast< ::QNetworkInterface::InterfaceFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QNetworkInterface_InterfaceFlags));

    if (!sipCpp)
        return -1;


    {
        {
            int sipRes = 0;

#line 111 "sip/QtCore/qglobal.sip"
        sipRes = (sipCpp->operator QNetworkInterface::InterfaceFlags::Int() != 0);
#line 76 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/QtNetwork/sipQtNetworkQNetworkInterfaceInterfaceFlags.cpp"

            return sipRes;
        }
    }

    return 0;
}


extern "C" {static PyObject *slot_QNetworkInterface_InterfaceFlags___ne__(PyObject *,PyObject *);}
static PyObject *slot_QNetworkInterface_InterfaceFlags___ne__(PyObject *sipSelf,PyObject *sipArg)
{
     ::QNetworkInterface::InterfaceFlags *sipCpp = reinterpret_cast< ::QNetworkInterface::InterfaceFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QNetworkInterface_InterfaceFlags));

    if (!sipCpp)
        return SIP_NULLPTR;

    PyObject *sipParseErr = SIP_NULLPTR;

    {
        const  ::QNetworkInterface::InterfaceFlags* a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QNetworkInterface_InterfaceFlags, &a0, &a0State))
        {
            bool sipRes = 0;

#line 106 "sip/QtCore/qglobal.sip"
        sipRes = (sipCpp->operator QNetworkInterface::InterfaceFlags::Int() != a0->operator QNetworkInterface::InterfaceFlags::Int());
#line 106 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/QtNetwork/sipQtNetworkQNetworkInterfaceInterfaceFlags.cpp"
            sipReleaseType(const_cast< ::QNetworkInterface::InterfaceFlags *>(a0),sipType_QNetworkInterface_InterfaceFlags,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return SIP_NULLPTR;

    return sipPySlotExtend(&sipModuleAPI_QtNetwork, ne_slot, sipType_QNetworkInterface_InterfaceFlags, sipSelf, sipArg);
}


extern "C" {static PyObject *slot_QNetworkInterface_InterfaceFlags___eq__(PyObject *,PyObject *);}
static PyObject *slot_QNetworkInterface_InterfaceFlags___eq__(PyObject *sipSelf,PyObject *sipArg)
{
     ::QNetworkInterface::InterfaceFlags *sipCpp = reinterpret_cast< ::QNetworkInterface::InterfaceFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QNetworkInterface_InterfaceFlags));

    if (!sipCpp)
        return SIP_NULLPTR;

    PyObject *sipParseErr = SIP_NULLPTR;

    {
        const  ::QNetworkInterface::InterfaceFlags* a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QNetworkInterface_InterfaceFlags, &a0, &a0State))
        {
            bool sipRes = 0;

#line 101 "sip/QtCore/qglobal.sip"
        sipRes = (sipCpp->operator QNetworkInterface::InterfaceFlags::Int() == a0->operator QNetworkInterface::InterfaceFlags::Int());
#line 142 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/QtNetwork/sipQtNetworkQNetworkInterfaceInterfaceFlags.cpp"
            sipReleaseType(const_cast< ::QNetworkInterface::InterfaceFlags *>(a0),sipType_QNetworkInterface_InterfaceFlags,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return SIP_NULLPTR;

    return sipPySlotExtend(&sipModuleAPI_QtNetwork, eq_slot, sipType_QNetworkInterface_InterfaceFlags, sipSelf, sipArg);
}


extern "C" {static PyObject *slot_QNetworkInterface_InterfaceFlags___ixor__(PyObject *,PyObject *);}
static PyObject *slot_QNetworkInterface_InterfaceFlags___ixor__(PyObject *sipSelf,PyObject *sipArg)
{
    if (!PyObject_TypeCheck(sipSelf, sipTypeAsPyTypeObject(sipType_QNetworkInterface_InterfaceFlags)))
    {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }

     ::QNetworkInterface::InterfaceFlags *sipCpp = reinterpret_cast< ::QNetworkInterface::InterfaceFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QNetworkInterface_InterfaceFlags));

    if (!sipCpp)
        return SIP_NULLPTR;

    PyObject *sipParseErr = SIP_NULLPTR;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1i", &a0))
        {
#line 95 "sip/QtCore/qglobal.sip"
        *sipCpp = QNetworkInterface::InterfaceFlags(*sipCpp ^ a0);
#line 181 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/QtNetwork/sipQtNetworkQNetworkInterfaceInterfaceFlags.cpp"

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return SIP_NULLPTR;

    PyErr_Clear();

    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}


extern "C" {static PyObject *slot_QNetworkInterface_InterfaceFlags___xor__(PyObject *,PyObject *);}
static PyObject *slot_QNetworkInterface_InterfaceFlags___xor__(PyObject *sipArg0,PyObject *sipArg1)
{
    PyObject *sipParseErr = SIP_NULLPTR;

    {
         ::QNetworkInterface::InterfaceFlags* a0;
        int a0State = 0;
        int a1;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J1i", sipType_QNetworkInterface_InterfaceFlags, &a0, &a0State, &a1))
        {
             ::QNetworkInterface::InterfaceFlags*sipRes;

            sipRes = new  ::QNetworkInterface::InterfaceFlags((*a0 ^ a1));
            sipReleaseType(a0,sipType_QNetworkInterface_InterfaceFlags,a0State);

            return sipConvertFromNewType(sipRes,sipType_QNetworkInterface_InterfaceFlags,SIP_NULLPTR);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return SIP_NULLPTR;

    return sipPySlotExtend(&sipModuleAPI_QtNetwork, xor_slot, SIP_NULLPTR, sipArg0, sipArg1);
}


extern "C" {static PyObject *slot_QNetworkInterface_InterfaceFlags___ior__(PyObject *,PyObject *);}
static PyObject *slot_QNetworkInterface_InterfaceFlags___ior__(PyObject *sipSelf,PyObject *sipArg)
{
    if (!PyObject_TypeCheck(sipSelf, sipTypeAsPyTypeObject(sipType_QNetworkInterface_InterfaceFlags)))
    {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }

     ::QNetworkInterface::InterfaceFlags *sipCpp = reinterpret_cast< ::QNetworkInterface::InterfaceFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QNetworkInterface_InterfaceFlags));

    if (!sipCpp)
        return SIP_NULLPTR;

    PyObject *sipParseErr = SIP_NULLPTR;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1i", &a0))
        {
#line 89 "sip/QtCore/qglobal.sip"
        *sipCpp = QNetworkInterface::InterfaceFlags(*sipCpp | a0);
#line 253 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/QtNetwork/sipQtNetworkQNetworkInterfaceInterfaceFlags.cpp"

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return SIP_NULLPTR;

    PyErr_Clear();

    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}


extern "C" {static PyObject *slot_QNetworkInterface_InterfaceFlags___or__(PyObject *,PyObject *);}
static PyObject *slot_QNetworkInterface_InterfaceFlags___or__(PyObject *sipArg0,PyObject *sipArg1)
{
    PyObject *sipParseErr = SIP_NULLPTR;

    {
         ::QNetworkInterface::InterfaceFlags* a0;
        int a0State = 0;
        int a1;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J1i", sipType_QNetworkInterface_InterfaceFlags, &a0, &a0State, &a1))
        {
             ::QNetworkInterface::InterfaceFlags*sipRes;

            sipRes = new  ::QNetworkInterface::InterfaceFlags((*a0 | a1));
            sipReleaseType(a0,sipType_QNetworkInterface_InterfaceFlags,a0State);

            return sipConvertFromNewType(sipRes,sipType_QNetworkInterface_InterfaceFlags,SIP_NULLPTR);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return SIP_NULLPTR;

    return sipPySlotExtend(&sipModuleAPI_QtNetwork, or_slot, SIP_NULLPTR, sipArg0, sipArg1);
}


extern "C" {static PyObject *slot_QNetworkInterface_InterfaceFlags___iand__(PyObject *,PyObject *);}
static PyObject *slot_QNetworkInterface_InterfaceFlags___iand__(PyObject *sipSelf,PyObject *sipArg)
{
    if (!PyObject_TypeCheck(sipSelf, sipTypeAsPyTypeObject(sipType_QNetworkInterface_InterfaceFlags)))
    {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }

     ::QNetworkInterface::InterfaceFlags *sipCpp = reinterpret_cast< ::QNetworkInterface::InterfaceFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QNetworkInterface_InterfaceFlags));

    if (!sipCpp)
        return SIP_NULLPTR;

    PyObject *sipParseErr = SIP_NULLPTR;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1i", &a0))
        {
            sipCpp-> ::QNetworkInterface::InterfaceFlags::operator&=(a0);

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return SIP_NULLPTR;

    PyErr_Clear();

    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}


extern "C" {static PyObject *slot_QNetworkInterface_InterfaceFlags___and__(PyObject *,PyObject *);}
static PyObject *slot_QNetworkInterface_InterfaceFlags___and__(PyObject *sipArg0,PyObject *sipArg1)
{
    PyObject *sipParseErr = SIP_NULLPTR;

    {
         ::QNetworkInterface::InterfaceFlags* a0;
        int a0State = 0;
        int a1;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J1i", sipType_QNetworkInterface_InterfaceFlags, &a0, &a0State, &a1))
        {
             ::QNetworkInterface::InterfaceFlags*sipRes;

            sipRes = new  ::QNetworkInterface::InterfaceFlags((*a0 & a1));
            sipReleaseType(a0,sipType_QNetworkInterface_InterfaceFlags,a0State);

            return sipConvertFromNewType(sipRes,sipType_QNetworkInterface_InterfaceFlags,SIP_NULLPTR);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return SIP_NULLPTR;

    return sipPySlotExtend(&sipModuleAPI_QtNetwork, and_slot, SIP_NULLPTR, sipArg0, sipArg1);
}


extern "C" {static PyObject *slot_QNetworkInterface_InterfaceFlags___invert__(PyObject *);}
static PyObject *slot_QNetworkInterface_InterfaceFlags___invert__(PyObject *sipSelf)
{
     ::QNetworkInterface::InterfaceFlags *sipCpp = reinterpret_cast< ::QNetworkInterface::InterfaceFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QNetworkInterface_InterfaceFlags));

    if (!sipCpp)
        return SIP_NULLPTR;


    {
        {
             ::QNetworkInterface::InterfaceFlags*sipRes;

            sipRes = new  ::QNetworkInterface::InterfaceFlags(~(*sipCpp));

            return sipConvertFromNewType(sipRes,sipType_QNetworkInterface_InterfaceFlags,SIP_NULLPTR);
        }
    }

    return 0;
}


extern "C" {static PyObject *slot_QNetworkInterface_InterfaceFlags___int__(PyObject *);}
static PyObject *slot_QNetworkInterface_InterfaceFlags___int__(PyObject *sipSelf)
{
     ::QNetworkInterface::InterfaceFlags *sipCpp = reinterpret_cast< ::QNetworkInterface::InterfaceFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QNetworkInterface_InterfaceFlags));

    if (!sipCpp)
        return SIP_NULLPTR;


    {
        {
            int sipRes;

            sipRes = *sipCpp;

            return PyLong_FromLong(sipRes);
        }
    }

    return 0;
}


/* Call the instance's destructor. */
extern "C" {static void release_QNetworkInterface_InterfaceFlags(void *, int);}
static void release_QNetworkInterface_InterfaceFlags(void *sipCppV, int)
{
    delete reinterpret_cast< ::QNetworkInterface::InterfaceFlags *>(sipCppV);
}


extern "C" {static void *array_QNetworkInterface_InterfaceFlags(Py_ssize_t);}
static void *array_QNetworkInterface_InterfaceFlags(Py_ssize_t sipNrElem)
{
    return new  ::QNetworkInterface::InterfaceFlags[sipNrElem];
}


extern "C" {static void assign_QNetworkInterface_InterfaceFlags(void *, Py_ssize_t, void *);}
static void assign_QNetworkInterface_InterfaceFlags(void *sipDst, Py_ssize_t sipDstIdx, void *sipSrc)
{
    reinterpret_cast< ::QNetworkInterface::InterfaceFlags *>(sipDst)[sipDstIdx] = *reinterpret_cast< ::QNetworkInterface::InterfaceFlags *>(sipSrc);
}


extern "C" {static void *copy_QNetworkInterface_InterfaceFlags(const void *, Py_ssize_t);}
static void *copy_QNetworkInterface_InterfaceFlags(const void *sipSrc, Py_ssize_t sipSrcIdx)
{
    return new  ::QNetworkInterface::InterfaceFlags(reinterpret_cast<const  ::QNetworkInterface::InterfaceFlags *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_QNetworkInterface_InterfaceFlags(sipSimpleWrapper *);}
static void dealloc_QNetworkInterface_InterfaceFlags(sipSimpleWrapper *sipSelf)
{
    if (sipIsOwnedByPython(sipSelf))
    {
        release_QNetworkInterface_InterfaceFlags(sipGetAddress(sipSelf), 0);
    }
}


extern "C" {static void *init_type_QNetworkInterface_InterfaceFlags(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_QNetworkInterface_InterfaceFlags(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
     ::QNetworkInterface::InterfaceFlags *sipCpp = SIP_NULLPTR;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, SIP_NULLPTR, sipUnused, ""))
        {
            sipCpp = new  ::QNetworkInterface::InterfaceFlags();

            return sipCpp;
        }
    }

    {
        int a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, SIP_NULLPTR, sipUnused, "i", &a0))
        {
            sipCpp = new  ::QNetworkInterface::InterfaceFlags(a0);

            return sipCpp;
        }
    }

    {
        const  ::QNetworkInterface::InterfaceFlags* a0;
        int a0State = 0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, SIP_NULLPTR, sipUnused, "J1", sipType_QNetworkInterface_InterfaceFlags, &a0, &a0State))
        {
            sipCpp = new  ::QNetworkInterface::InterfaceFlags(*a0);
            sipReleaseType(const_cast< ::QNetworkInterface::InterfaceFlags *>(a0),sipType_QNetworkInterface_InterfaceFlags,a0State);

            return sipCpp;
        }
    }

    return SIP_NULLPTR;
}


extern "C" {static int convertTo_QNetworkInterface_InterfaceFlags(PyObject *, void **, int *, PyObject *);}
static int convertTo_QNetworkInterface_InterfaceFlags(PyObject *sipPy,void **sipCppPtrV,int *sipIsErr,PyObject *sipTransferObj)
{
     ::QNetworkInterface::InterfaceFlags **sipCppPtr = reinterpret_cast< ::QNetworkInterface::InterfaceFlags **>(sipCppPtrV);

#line 121 "sip/QtCore/qglobal.sip"
// Allow an instance of the base enum whenever a QNetworkInterface::InterfaceFlags is expected.

if (sipIsErr == NULL)
    return (PyObject_TypeCheck(sipPy, sipTypeAsPyTypeObject(sipType_QNetworkInterface_InterfaceFlag)) ||
            sipCanConvertToType(sipPy, sipType_QNetworkInterface_InterfaceFlags, SIP_NO_CONVERTORS));

if (PyObject_TypeCheck(sipPy, sipTypeAsPyTypeObject(sipType_QNetworkInterface_InterfaceFlag)))
{
    *sipCppPtr = new QNetworkInterface::InterfaceFlags(int(SIPLong_AsLong(sipPy)));

    return sipGetState(sipTransferObj);
}

*sipCppPtr = reinterpret_cast<QNetworkInterface::InterfaceFlags *>(sipConvertToType(sipPy, sipType_QNetworkInterface_InterfaceFlags, sipTransferObj, SIP_NO_CONVERTORS, 0, sipIsErr));

return 0;
#line 521 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/QtNetwork/sipQtNetworkQNetworkInterfaceInterfaceFlags.cpp"
}


/* Define this type's Python slots. */
static sipPySlotDef slots_QNetworkInterface_InterfaceFlags[] = {
    {(void *)slot_QNetworkInterface_InterfaceFlags___hash__, hash_slot},
    {(void *)slot_QNetworkInterface_InterfaceFlags___bool__, bool_slot},
    {(void *)slot_QNetworkInterface_InterfaceFlags___ne__, ne_slot},
    {(void *)slot_QNetworkInterface_InterfaceFlags___eq__, eq_slot},
    {(void *)slot_QNetworkInterface_InterfaceFlags___ixor__, ixor_slot},
    {(void *)slot_QNetworkInterface_InterfaceFlags___xor__, xor_slot},
    {(void *)slot_QNetworkInterface_InterfaceFlags___ior__, ior_slot},
    {(void *)slot_QNetworkInterface_InterfaceFlags___or__, or_slot},
    {(void *)slot_QNetworkInterface_InterfaceFlags___iand__, iand_slot},
    {(void *)slot_QNetworkInterface_InterfaceFlags___and__, and_slot},
    {(void *)slot_QNetworkInterface_InterfaceFlags___invert__, invert_slot},
    {(void *)slot_QNetworkInterface_InterfaceFlags___int__, int_slot},
    {0, (sipPySlotType)0}
};

PyDoc_STRVAR(doc_QNetworkInterface_InterfaceFlags, "\1QNetworkInterface.InterfaceFlags()\n"
"QNetworkInterface.InterfaceFlags(Union[QNetworkInterface.InterfaceFlags, QNetworkInterface.InterfaceFlag])\n"
"QNetworkInterface.InterfaceFlags(QNetworkInterface.InterfaceFlags)");


static pyqt5ClassPluginDef plugin_QNetworkInterface_InterfaceFlags = {
    SIP_NULLPTR,
    1,
    SIP_NULLPTR,
    SIP_NULLPTR
};


sipClassTypeDef sipTypeDef_QtNetwork_QNetworkInterface_InterfaceFlags = {
    {
        -1,
        SIP_NULLPTR,
        SIP_NULLPTR,
        SIP_TYPE_SUPER_INIT|SIP_TYPE_LIMITED_API|SIP_TYPE_CLASS,
        sipNameNr_QNetworkInterface__InterfaceFlags,
        SIP_NULLPTR,
        &plugin_QNetworkInterface_InterfaceFlags
    },
    {
        sipNameNr_InterfaceFlags,
        {77, 255, 0},
        0, SIP_NULLPTR,
        0, SIP_NULLPTR,
        0, SIP_NULLPTR,
        {SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR},
    },
    doc_QNetworkInterface_InterfaceFlags,
    -1,
    sipNameNr_sip_simplewrapper,
    SIP_NULLPTR,
    slots_QNetworkInterface_InterfaceFlags,
    init_type_QNetworkInterface_InterfaceFlags,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    dealloc_QNetworkInterface_InterfaceFlags,
    assign_QNetworkInterface_InterfaceFlags,
    array_QNetworkInterface_InterfaceFlags,
    copy_QNetworkInterface_InterfaceFlags,
    release_QNetworkInterface_InterfaceFlags,
    SIP_NULLPTR,
    convertTo_QNetworkInterface_InterfaceFlags,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR
};
