/*
 * Interface wrapper code.
 *
 * Generated by SIP 5.3.0
 *
 * Copyright (c) 2019 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt5.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtGui.h"

#line 451 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/sip/QtGui/qevent.sip"
#include <qevent.h>
#line 29 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/QtGui/sipQtGuiQShowEvent.cpp"

#line 26 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 33 "/home/fernandaabreu/projetos/MyTicketsSearcher/PyQt5-5.13.2/QtGui/sipQtGuiQShowEvent.cpp"


class sipQShowEvent : public  ::QShowEvent
{
public:
    sipQShowEvent();
    sipQShowEvent(const  ::QShowEvent&);
    ~sipQShowEvent();

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipQShowEvent(const sipQShowEvent &);
    sipQShowEvent &operator = (const sipQShowEvent &);
};

sipQShowEvent::sipQShowEvent():  ::QShowEvent(), sipPySelf(SIP_NULLPTR)
{
}

sipQShowEvent::sipQShowEvent(const  ::QShowEvent& a0):  ::QShowEvent(a0), sipPySelf(SIP_NULLPTR)
{
}

sipQShowEvent::~sipQShowEvent()
{
    sipInstanceDestroyedEx(&sipPySelf);
}


/* Cast a pointer to a type somewhere in its inheritance hierarchy. */
extern "C" {static void *cast_QShowEvent(void *, const sipTypeDef *);}
static void *cast_QShowEvent(void *sipCppV, const sipTypeDef *targetType)
{
     ::QShowEvent *sipCpp = reinterpret_cast< ::QShowEvent *>(sipCppV);

    if (targetType == sipType_QEvent)
        return static_cast< ::QEvent *>(sipCpp);

    return sipCppV;
}


/* Call the instance's destructor. */
extern "C" {static void release_QShowEvent(void *, int);}
static void release_QShowEvent(void *sipCppV, int sipState)
{
    if (sipState & SIP_DERIVED_CLASS)
        delete reinterpret_cast<sipQShowEvent *>(sipCppV);
    else
        delete reinterpret_cast< ::QShowEvent *>(sipCppV);
}


extern "C" {static void *array_QShowEvent(Py_ssize_t);}
static void *array_QShowEvent(Py_ssize_t sipNrElem)
{
    return new  ::QShowEvent[sipNrElem];
}


extern "C" {static void assign_QShowEvent(void *, Py_ssize_t, void *);}
static void assign_QShowEvent(void *sipDst, Py_ssize_t sipDstIdx, void *sipSrc)
{
    reinterpret_cast< ::QShowEvent *>(sipDst)[sipDstIdx] = *reinterpret_cast< ::QShowEvent *>(sipSrc);
}


extern "C" {static void *copy_QShowEvent(const void *, Py_ssize_t);}
static void *copy_QShowEvent(const void *sipSrc, Py_ssize_t sipSrcIdx)
{
    return new  ::QShowEvent(reinterpret_cast<const  ::QShowEvent *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_QShowEvent(sipSimpleWrapper *);}
static void dealloc_QShowEvent(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerivedClass(sipSelf))
        reinterpret_cast<sipQShowEvent *>(sipGetAddress(sipSelf))->sipPySelf = SIP_NULLPTR;

    if (sipIsOwnedByPython(sipSelf))
    {
        release_QShowEvent(sipGetAddress(sipSelf), sipIsDerivedClass(sipSelf));
    }
}


extern "C" {static void *init_type_QShowEvent(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_QShowEvent(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    sipQShowEvent *sipCpp = SIP_NULLPTR;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, SIP_NULLPTR, sipUnused, ""))
        {
            sipCpp = new sipQShowEvent();

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    {
        const  ::QShowEvent* a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, SIP_NULLPTR, sipUnused, "J9", sipType_QShowEvent, &a0))
        {
            sipCpp = new sipQShowEvent(*a0);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return SIP_NULLPTR;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QShowEvent[] = {{6, 0, 1}};

PyDoc_STRVAR(doc_QShowEvent, "\1QShowEvent()\n"
"QShowEvent(QShowEvent)");


static pyqt5ClassPluginDef plugin_QShowEvent = {
    SIP_NULLPTR,
    0,
    SIP_NULLPTR,
    SIP_NULLPTR
};


sipClassTypeDef sipTypeDef_QtGui_QShowEvent = {
    {
        -1,
        SIP_NULLPTR,
        SIP_NULLPTR,
        SIP_TYPE_SCC|SIP_TYPE_SUPER_INIT|SIP_TYPE_LIMITED_API|SIP_TYPE_CLASS,
        sipNameNr_QShowEvent,
        SIP_NULLPTR,
        &plugin_QShowEvent
    },
    {
        sipNameNr_QShowEvent,
        {0, 0, 1},
        0, SIP_NULLPTR,
        0, SIP_NULLPTR,
        0, SIP_NULLPTR,
        {SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR},
    },
    doc_QShowEvent,
    -1,
    -1,
    supers_QShowEvent,
    SIP_NULLPTR,
    init_type_QShowEvent,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    dealloc_QShowEvent,
    assign_QShowEvent,
    array_QShowEvent,
    copy_QShowEvent,
    release_QShowEvent,
    cast_QShowEvent,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR
};
